/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'primary': '#0e7c46',
        'primary-container': '#10a95a',
        'primary-fixed': '#d4f5e1',
        'primary-fixed-dim': '#a8e8c4',
        'on-primary': '#ffffff',
        'on-primary-container': '#edfdf2',
        'on-primary-fixed': '#002110',
        'on-primary-fixed-variant': '#00582f',
        'inverse-primary': '#a8e8c4',
        'surface': '#f7fbf8',
        'surface-base': '#F8FAFC',
        'surface-bright': '#f7fbf8',
        'surface-card': '#FFFFFF',
        'surface-subtle': '#F8FAFC',
        'surface-canvas': '#FFFFFF',
        'surface-container': '#e7f5ec',
        'surface-container-low': '#eff8f2',
        'surface-container-high': '#dcf0e3',
        'surface-container-highest': '#d0eada',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#c8d9cd',
        'surface-variant': '#d0eada',
        'surface-tint': '#12944e',
        'on-surface': '#0b1f13',
        'on-surface-variant': '#414942',
        'inverse-surface': '#213126',
        'outline': '#717971',
        'outline-variant': '#c1c9c0',
        // Example-specific tokens
        'text-primary': '#0F172A',
        'text-secondary': '#475569',
        'text-muted': '#64748B',
        'brand-emerald-vibrant': '#10B981',
        'surface-emerald-subtle': '#DCFCE7',
        'surface-emerald-tint': '#F0FDF4',
        'alert-amber-text': '#92400E',
        'alert-rose-bg': '#FFF1F2',
        'alert-rose-text': '#9F1239',
        'info-blue-bg': '#F0F9FF',
        'info-blue-text': '#0369A1',
      },
      fontFamily: {
        'body': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body-default': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body-lead': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body-small': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body-bold': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'caption': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'label-badge': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'metric-large': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline-h1': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline-h2': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline-h3': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline-h4': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        // Original sizes (kept)
        'body-sm': ['0.875rem', { lineHeight: '1.5' }],
        'body-md': ['1rem', { lineHeight: '1.6' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6' }],
        'headline-sm': ['1.125rem', { lineHeight: '1.4' }],
        'headline-md': ['1.5rem', { lineHeight: '1.3' }],
        'headline-lg': ['2rem', { lineHeight: '1.2' }],
        'headline-xl': ['2.5rem', { lineHeight: '1.1' }],
        // Example heading sizes
        'headline-h1': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '800' }],
        'headline-h2': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-h3': ['19px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-h4': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        // Body text sizes
        'body-default': ['16px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '400' }],
        'body-lead': ['18px', { lineHeight: '30px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-small': ['14px', { lineHeight: '22px', letterSpacing: '0.005em', fontWeight: '400' }],
        'body-bold': ['16px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '600' }],
        // Labels & captions
        'caption': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-badge': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '700' }],
        'metric-large': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      spacing: {
        'gutter-mobile': '1rem',
        'gutter': '1.5rem',
        'gutter-sm': '1rem',
        'gutter-lg': '2.5rem',
        'gutter-desktop': '1.5rem',
        'margin': '1.5rem',
        'margin-tablet': '2rem',
        'margin-desktop': '3rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
      },
      borderRadius: {
        'card': '1rem',
        'button': '0.75rem',
        'input': '0.5rem',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.03)',
        'card-hover': '0 4px 16px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
};
