/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'primary': '#0e7c46',
        'primary-container': '#10a95a',
        'primary-fixed': '#d4f5e1',
        'primary-fixed-dim': '#a8e8c4',
        'on-primary': '#ffffff',
        'on-primary-container': '#edfdf2',
        'on-primary-fixed': '#002110',
        'on-primary-fixed-variant': '#00582f',
        'inverse-primary': '#a8e8c4',
        'surface': '#f7fbf8',
        'surface-base': '#F8FAFC',
        'surface-bright': '#f7fbf8',
        'surface-card': '#FFFFFF',
        'surface-container': '#e7f5ec',
        'surface-container-low': '#eff8f2',
        'surface-container-high': '#dcf0e3',
        'surface-container-highest': '#d0eada',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#c8d9cd',
        'surface-variant': '#d0eada',
        'surface-tint': '#12944e',
        'on-surface': '#0b1f13',
        'on-surface-variant': '#414942',
        'inverse-surface': '#213126',
        'outline': '#717971',
        'outline-variant': '#c1c9c0',
      },
      fontFamily: {
        'body': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['0.875rem', { lineHeight: '1.5' }],
        'body-md': ['1rem', { lineHeight: '1.6' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6' }],
        'headline-sm': ['1.125rem', { lineHeight: '1.4' }],
        'headline-md': ['1.5rem', { lineHeight: '1.3' }],
        'headline-lg': ['2rem', { lineHeight: '1.2' }],
        'headline-xl': ['2.5rem', { lineHeight: '1.1' }],
      },
      spacing: {
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
      },
      borderRadius: {
        'card': '1rem',
        'button': '0.75rem',
        'input': '0.5rem',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.03)',
        'card-hover': '0 4px 16px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
};
