/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'primary': '#004632',
        'primary-container': '#0d5f46',
        'primary-fixed': '#a8f2d1',
        'primary-fixed-dim': '#8cd5b6',
        'on-primary': '#ffffff',
        'on-primary-container': '#8ed6b7',
        'on-primary-fixed': '#002116',
        'on-primary-fixed-variant': '#00513b',
        'inverse-primary': '#8cd5b6',
        'surface': '#f9f9ff',
        'surface-bright': '#f9f9ff',
        'surface-card': '#FFFFFF',
        'surface-subtle': '#F8FAFC',
        'surface-canvas': '#FFFFFF',
        'surface-container': '#e7eeff',
        'surface-container-low': '#f0f3ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'surface-dim': '#cfdaf2',
        'surface-variant': '#d8e3fb',
        'surface-emerald-subtle': '#DCFCE7',
        'surface-emerald-tint': '#F0FDF4',
        'surface-tint': '#1f6a51',
        'on-surface': '#111c2d',
        'on-surface-variant': '#3f4944',
        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',
        'outline': '#6f7973',
        'outline-variant': '#bfc9c2',
        'text-primary': '#0F172A',
        'text-secondary': '#475569',
        'text-muted': '#64748B',
        'background': '#f9f9ff',
        'on-background': '#111c2d',
        'secondary': '#006c4e',
        'secondary-container': '#97f5cc',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#007353',
        'on-secondary-fixed': '#002115',
        'on-secondary-fixed-variant': '#00513a',
        'secondary-fixed': '#97f5cc',
        'secondary-fixed-dim': '#7bd8b1',
        'tertiary': '#343c51',
        'tertiary-container': '#4b5369',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#bfc7e1',
        'on-tertiary-fixed': '#131b2e',
        'on-tertiary-fixed-variant': '#3f465c',
        'tertiary-fixed': '#dae2fd',
        'tertiary-fixed-dim': '#bec6e0',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'brand-emerald-vibrant': '#10B981',
        'brand-forest-dark': '#064E3B',
        'border-strong': '#CBD5E1',
        'border-subtle': '#E2E8F0',
        'alert-amber-bg': '#FFFBEB',
        'alert-amber-border': '#FDE68A',
        'alert-amber-text': '#92400E',
        'alert-rose-bg': '#FFF1F2',
        'alert-rose-border': '#FECDD3',
        'alert-rose-text': '#9F1239',
        'info-blue-bg': '#F0F9FF',
        'info-blue-border': '#BAE6FD',
        'info-blue-text': '#0369A1',
      },
      fontFamily: {
        'body': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body-default': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body-lead': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body-small': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'body-bold': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'caption': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'label-badge': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'metric-large': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline-h1': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline-h2': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline-h3': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        'headline-h4': ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        // Body sizes
        'body-sm': ['0.875rem', { lineHeight: '1.5' }],
        'body-md': ['1rem', { lineHeight: '1.6' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6' }],
        'body-default': ['16px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '400' }],
        'body-lead': ['18px', { lineHeight: '30px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-small': ['14px', { lineHeight: '22px', letterSpacing: '0.005em', fontWeight: '400' }],
        'body-bold': ['16px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '600' }],
        // Headline sizes
        'headline-sm': ['1.125rem', { lineHeight: '1.4' }],
        'headline-md': ['1.5rem', { lineHeight: '1.3' }],
        'headline-lg': ['2rem', { lineHeight: '1.2' }],
        'headline-xl': ['2.5rem', { lineHeight: '1.1' }],
        'headline-h1': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '800' }],
        'headline-h2': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-h3': ['19px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-h4': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '600' }],
        'headline-h1-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-h2-mobile': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '700' }],
        // Display
        'display-hero': ['44px', { lineHeight: '52px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-hero-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.025em', fontWeight: '800' }],
        // Caption & labels
        'caption': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-badge': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '700' }],
        'metric-large': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      spacing: {
        'gutter-mobile': '1rem',
        'gutter': '1.5rem',
        'gutter-sm': '1rem',
        'gutter-lg': '2.5rem',
        'gutter-desktop': '1.5rem',
        'margin': '1.5rem',
        'margin-tablet': '2rem',
        'margin-desktop': '3rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4.5rem',
      },
      borderRadius: {
        'card': '1rem',
        'button': '0.75rem',
        'input': '0.5rem',
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.03)',
        'card-hover': '0 4px 16px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
};
